language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: IXtR0NPXOjVMlhDuEZjhdL4MpvPWNrLEab9iSOpz+uF6/+GQoi0nzLtFNzfT4WQAmvADLORatw0ojBkAyYfzHFK8I39s53noy1iskSWm1BXPLcbURgrIzLaSCJiE93dpCWNWWOTW6ReRrtLKOtjZpeOIWs70IjCDXt4h+2W5BTCUsbUtf9J+Ps2UxwQ2sh40Ieevfyc7j6JLuKTu5d/a4Lg0sH+RiEYNKB1lTIcRrgWL2oghxVBIzKLR88ljSlRK+sX/Rfg4XaDz5QyvLm6feeqUrvkJ5xTU4YAEdnZ9oCP3cYvv9+/5gK8jmdRBdqfS2T0W5rcAc6sGrecaYurHm0mHhXfjMdmUBP0TzeSlF/sEoA/LduJBvmwszsPmatdKlN7ft812+c7ut2Bm8OTQEQBq7yK+z4up7O1Cg9z5LUXrMa/K+/MlWwq9RH6QbkrpOZOB6cioXSNt5TQNVLM9koIKiB0sLhwkCEYHIcea3wco1sxkRyHg33R6O3z5D8BE2cXBKTcSVqkJulYgTU95eXLVBHU/HVuCad7mJ34lBssgHmrtoG7BdWw/3LwiC8UlUw8eERyer9378U2MIP9ZVg/p041T/HP0sU8kXLx2Y3cE7auf//g4A2QtmrghEliWRHuGhCjX92Ehnm/WYzorOwpBTe+io4G7DJHtZFBFeD8=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: M6TGGeDl2HJJQ6PxnxwWDTs0Cc6kNA4LhxYt+0z+cTouFrmc9fe+uu3SFzjU5odIVfa12sCOKOy2Fm6Gjfsicz3D3BnlVkrocwY9nzX4vIF4PlM+ptTd8Wkm0A4/clTOOGERglp2jPW1rtyL2XzcTW3Sam5bBmoHThXdiw234RtilGZTw8fYlcCuDGSz5MnLowtYrIKzhM8ltiBUq5El1YYqLrMtuJlolEd7TGwjcG8Fg2lT9GmI5shIcd5dwUjvoGhKkzdr6X+GuWnGG24JVET4eImdVuETsHRqxJvVwQgqkJXHayGLwMOFtA0I/95un16RTduf+j1L5RbGYL+hf0zcBZmgHFcrqnj9mhZkfXwcLiYdJ18T8bRpU1a0F+o4KKRBXDHH0bwYaSASabKVtWf5tP3N/SxP43IryX1ht9TkXvMBJAMAaszQcaeUoS9KnSzbPNikfzDEJ5kKbJfrzZV8jyed8MomBaKf/U7wkOUha1SWC4ucIL9XtY7vxT+BWX0qGnx7mQ6ZOf3uhSyforCsqbJfa60MRXJXXNT9TvVdaFs9c1fjmdBN3IXaJlXkAuwdkIHvS3Ov5NKp7PRUgcp1P24xe5/tLBi9+7Wq9uOL6lZHy682C41eTX1TorPFiYxrIYF16YqJEY35IJOnJ1AveG1dO/qjMxDhgmtj+8s=
  - secure: 0L3YU6j4TngMEAobU5c4qdLpI8cxbS3VERDIikroAcZ9BnejsPTj8DdxUPoJOr786Ms1G6DdYrbW6ec/dhpfoxzPbAmWK8OAqqxYtxmEqKMH9c5fDOk917Wvgrrk+j9Lb+DO2GaOB910UP6JuDEqQQ9yzaAssRWA6ZzG99GQLQAFW3AZZdpkyo10laU+3Q4K3PlN9m/Hih+agbTm0ubJjirLE1KpAosTY6zAbam1QKXqpt0pwdHxQdrbEIlwfG5YFTPr/IgH42GydXOm3jsjt5ksd7C+lwiVs32SCIKSHYz3LfU7J0HGByRpYbhPDWmn7gD6uJO0xuVdeV6E9lIZPa9evOU2JloixI0BfYXBxxHAnxR/BK74OAsfgo3yfd14pN7Pb3ZGCHP0Yk9WxmHZADZG9UyUmR9hb5y5xnRwJ4HLA0iA0ZE6AalAumsW+Qklheoj1HKCPea0pEIG4oUH5tkqi5XFFN26+AYAUcmTwcS/m/l20u5XSWcXt/yknBE6ydmU+tcqaeO61UXqy0S+8SfXUUMU5X5v6pGl7XmkXlrMDlpBQWxuZs+/ScAI9k5uxKFIXSHyjcO+1Rc87V7pkdeiZQeef95XfcgeWK2mdfdqglQsqrPlRh7LufnL02hKZ7Edzu5iPV9lZvabPiix5vM7xbnfwll6fGyFeRQoPmo=
  - secure: LW9sDXo1ZutGPsBTeVt+esQGvj/eyAUBHQudXMSYXcBm/a3MbYYSB1t010oAEKQgBtqxZk3qyigqK6SSKFwhfvjK0K9dcV8Zu4Srp+Zrw/UnoWCx47KXp0eTo9AvWhn86dLvBkUBzELzgqe/2iloy3eNp2l/gDsTBBEnpBM7VLapyqPE1nXzNVrJI1qANNEV1JfdUSI2f+/B589FYW8ZeMpqPm7748YTwPQ+laJ0n4v6y71hiA1CXxasNduwOVZPx9E6jhYXJ8tlKCRCZorR0zAwYW21LZx8/lJBFHYNxo8FroTGznAGNWDsuHTDSl7DQX6xvnf09XcXSTKhrR1YHQ+LsbqrtVPfjDhdlOvNrqFCYmh8HGBsBxEattiNwpvm4iLUET10yRcGGVYHAIqbriICMGAe3HoFF5n+XjjrTV3Kf3d/8Lhvg1Ko7EOTkAq62J75vRt2LIGtpxOqBuaPdpPyvGcqeVpWSpcVFbpzJGR08r3PaD5dNAR5DdrBUasBGNANtzsCb4jPuHyZxmlVv14CGObBNtHRhu7vqEOm7a+c3NL6S4+jeFdIEvGa5mN1tGyxUm7nJXUIHE/KioBS1CZ14ovGNZOBDm4Ci7fB7C3NxarrazMSRTRE6x4yoD60hAd7Rc0zeTMHjBJo3pwio1GGGV5Gnd4nx4RqkDgBK9o=
  - secure: ZaAZedGyiRNGbAJ3Z5n9yx7csmUyBw8F0gUOA+CypLKSGUQo7eldnmtoDFdPim6MHM1FzE6wx+hhg5nnRVF1SZqbg4Q41Yu0YEBIZixekIWZSZQ+Xw92+8X6iy/HjEljtlIAlqs+6VK7syYTiQ5oMxK0n+7IwT+byRi6x3bVJ7mH4iufkzcytC9YHZDTCS3O0Q2VU5jeIb9px8eUPamDwn+aat0R+k8DkAaAxATC+vC4NgK3lBnTUqI06URrEMh2qAiWiAF2hTAzvpU0dsNHLpYGQO8FE5luN+fSQDZtt5YSAEBe/YxhkEoV8VuswRec/ROzb/nVrkRMB2B8Miic0rFYOgas8ddmh0nyJaSHXvMYScop4WbVIWvlkYlqOcyQ59nf8UCSlKFT7rbXbMf3Tv7hhlv+Hn/+aqW/5gqq/SIKli2cQRdiRA9jYXAhoi6Bk6/nxqwyNozfyNJeP28wXCijj3fFIL7D40HY8yaqpLFXrOVxORk5LQpU6iCK/Vi6F++0M8rUawQFKOTN/r4fyQCSoDxitRqP3PE5wdfNXg4qiibAWo17/FO9vtzKyFH18JKNhFBgEP6+SEeBQMH16sFD84N+6jjCiCZ2lUMX0jP4oQNkLVysFm+VhEW49YNhbfSYEVU2hLtU0GBSlhiItRLfuRInEEuRw+AhnHW9ZLI=
  - secure: BYLPubF1AltO6jYNaLdIPuul09qDmZTe6gzyN+4UR4DBTxho9WKSppfYrjdsH+YzUiY1e86tT49lC3WqwR5zVrWeBR7wPGWH8tiP8rksxmvHzbehmuEZP213c/pqyy8bnoLmd27JYSTfD5JQWypr2YLgjtoeSb31yBo2WXrM3OZCbFi+ewTIH+AZiFHfxHWIZWuWHMVM/WQYb8rkVyrNGfSuFOZKLjmfcHNhVklr3SGcbVTfVUqwpc/rGKTheIB+vXjAo+e2eoQysZAqYsQgkbC0kWqdQF4XohtbJb6nPau3Mj+7NIhWFxowq7WVoy/MqtJoAyh9bz4sioWQm5cPCHjR72q9QBxO6rWu4Lpozc0nJpHynY7PaG6HshvcjHXU2deyf6P0cU6Y4+Mg5iIjPPkIf9Br0pd+CLqAk6B96EsxIdgvs2NNGJRaw+M8vS8kfRJfZPEArJ7oL1eGMQtHLzn6JcEEDd2s29WlcfJRL9R8PWlp4OG7BOBOaa5edFVOc4vyl9uReOLy7eIAgLzl5aCSlbne0mQDVfedKPHCQBepub3NDfwjjxpvRw0CYMDKQy/dx86nQyfwLSZluyXJx4goL8zWEEqkDxgtJp8eH7KcKCLzpCioUXRtLkZqs0C9zDgQ4cbQQY30nKfNOoQd4dQ6put95A1keKQ19B/pTEo=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-confsvr-service:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE

#AWS desactive
#before_install:
#- gem install travis -v 1.8.5 --no-rdoc --no-ri
#- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
#- sudo chmod +x /usr/local/bin/ecs-cli
#- export BUILD_NAME=confsvr-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
#script:
#- sh scripts/travis/tag_build.sh
#- sh scripts/travis/build_services.sh
#- sh scripts/travis/deploy_to_docker_hub.sh
#- sh scripts/travis/deploy_to_amazon_ecs.sh
